board/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView
from views import BoardWizard, image_upload, image_delete
from forms import BoardForm, FlatForm, PriceForm, ImageForm


urlpatterns = [
    url(r'^image_upload/$', image_upload, name='image_upload'),
    url(r'^image_delete/$', image_delete, name='image_delete'),
    url(r'^create/$', TemplateView.as_view(template_name='board/board_create.html'), name='board_create_select'),
    url(r'^create/(?P<type_realty>[-\w]+)/$', BoardWizard.as_view([BoardForm, FlatForm, PriceForm, ImageForm]), name='board_create'),
]

otpusknikam/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from board.views import BoardListView, BoardDetailView, SearchListView, get_phone
from articles.views import ArticleListView, ArticleDetailView
from django.contrib.sitemaps import views as sitemaps_views
from sitemaps import sitemaps


if settings.DEBUG:

    urlpatterns = [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    ]

else:

    urlpatterns = []

urlpatterns += [
    url(r'^sitemap.xml$',
        sitemaps_views.index, {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'}),
    url(r'^(?P<section>.+)\.xml$',
        sitemaps_views.sitemap, {'sitemaps': sitemaps}, name='sitemaps'),
]

urlpatterns += [
    url(r'^$', BoardListView.as_view(), name='board_list'),
    url(r'^search/$', SearchListView.as_view(), name='search_list'),
    url(r'^user/(?P<user_pk>\d+)/$', BoardListView.as_view(), name='board_list_user'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^accounts/', include('users.urls')),
    url(r'^board/', include('board.urls')),
    url(r'^realty/$', ArticleListView.as_view(), name='article_list'),
    url(r'^realty/(?P<slug>[-_\w]+)/(?P<pk>\d+)\.html', ArticleDetailView.as_view(), name='article_detail'),
    url(r'^(?P<type_realty>[-\w]+)/$', BoardListView.as_view(), name='board_list_type_realty'),
    url(r'^(?P<type_realty>[-\w]+)/(?P<pk>\d+)/$', BoardDetailView.as_view(), name='board_detail'),
    url(r'^(?P<type_realty>[-\w]+)/(?P<pk>\d+)/phone\.js$', get_phone, name='board_phone'),
    url(r'^robots\.txt', 'robots.views.robots'),
    url(r'^', include('django.contrib.flatpages.urls')),
]

search/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from views import SearchListView


urlpatterns = patterns('',
    url(r'^$', SearchListView.as_view(), name='search_list'),
)

board/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.urlresolvers import reverse
from django.contrib.sites.models import Site
from django.conf import settings
from django.utils.safestring import mark_safe
from utils.models import upload_dir_class_name
from utils.validators import max_file_size_validator
from managers import ImageManager, BoardManager


TYPE_REALTY = [
    ('flat', u'Квартиру'),
    ('room', u'Комнату'),
    ('house', u'Дом'),
    ('hostel', u'Хостел'),
    ('mini', u'Мини-отель'),
    ('hotel', u'Гостиницу'),
    ('pension', u'Санаторий'),
]

TYPE_REALTY_NAME = {
    'flat': u'Квартира',
    'room': u'Комната',
    'house': u'Дом',
    'hostel': u'Хостел',
    'mini': u'Мини-отель',
    'hotel': u'Гостиница',
    'pension': u'Санаторий',
}

TYPE_REALTY_LIST = [x[0] for x in TYPE_REALTY]

PLACE = [
    ('city', u'В городе'),
    ('coast', u'На побережье'),
    ('town', u'В поселке'),
    ('river', u'У реки'),
    ('forest', u'В лесу'),
    ('river', u'На берегу озера'),
    ('village', u'В сельской местности'),
    ('mountain', u'В горах'),
]

TYPE_BEACH = [
    ('pebble', u'Галечный'),
    ('sand', u'Песчаный'),
    ('concrete', u'Бетонный'),
]

MOVE = [
    ('afoot', u'Пешком'),
    ('transport', u'На транспорте'),
]

STATUS = [
    ('owner', u'Собственник'),
    ('agency', u'Агентство'),
]

ROOM_COUNT = [
    (0, u'Студия'),
    (1, u'1'),
    (2, u'2'),
    (3, u'3'),
    (4, u'4'),
    (5, u'5 и больше'),
]

TYPE_HOUSE = [
    ('panel', u'Панельный'),
    ('monolithic', u'Монолитный'),
    ('monolith-brick', u'Монолитно-кирпичный'),
    ('modular', u'Блочный'),
    ('brick', u'Кирпичный'),
    ('wood', u'Деревянный'),
]

REPAIR = [
    ('cosmetic', u'Косметический'),
    ('euro', u'Евро'),
    ('design', u'Дизайнерский'),
]

SHOWER = [
    ('number', u'В номере'),
    ('floor', u'На этаже'),
]

WC = [
    ('number', u'В номере'),
    ('floor', u'На этаже'),
]

COOKER = [
    ('gas', u'Газовая'),
    ('electric', u'Электрическая'),
]

TYPE_BED = [
    ('single', u'Односпальная'),
    ('double', u'Двуспальная'),
]

PUBLISHED, UNPUBLISHED = 0, 1
STATUS_BOARD = {
    PUBLISHED: u'Опубликовано',
    UNPUBLISHED: u'Скрыто',
}

MAX_FILE_SIZE = getattr(settings, 'MAX_FILE_SIZE_UPLOAD', 0)
if MAX_FILE_SIZE:
    FILE_SIZE_HELP_TEXT = u'Максимальный размер загружаемого файла не должен превышать {filesize}МБ.'.format(filesize=MAX_FILE_SIZE)
else:
    FILE_SIZE_HELP_TEXT = ''


class City(Site):

    city_name = models.CharField(u'город', max_length=255)
    where = models.CharField(u'в городе', max_length=255)
    head_verification = models.TextField(u'head meta теги', blank=True)
    metro = models.BooleanField(u'метро', default=False)

    class Meta:

        verbose_name = u'город'
        verbose_name_plural = u'города'
        ordering = ['city_name']

    def __unicode__(self):
        return self.city_name


class AddressMixin(models.Model):

    city = models.ForeignKey(City, verbose_name=u'город', null=True, blank=True)
    street = models.CharField(u'адрес', max_length=255)
    place = models.CharField(u'месторасположение', choices=PLACE, max_length=255, default='city', null=True, blank=True)
    type_beach = models.CharField(u'тип пляжа', choices=TYPE_BEACH, max_length=255, blank=True)
    metro = models.PositiveIntegerField(u'до метро мин.', null=True, blank=True)
    beach = models.PositiveIntegerField(u'до пляжа мин.', null=True, blank=True)
    move_metro = models.CharField(u'как', choices=MOVE, max_length=255, default='afoot', null=True, blank=True)
    move_beach = models.CharField(u'как', choices=MOVE, max_length=255, default='afoot', null=True, blank=True)
    landmark = models.TextField(u'как добраться', blank=True, help_text=u'Опишите как добраться до места. Обозначьте местные ориентиры. Укажите с какой стороны вход в здание.')

    class Meta:

        abstract = True

    @property
    def address(self):
        return u'{city}, {street}'.format(city=self.city, street=self.street)


class ContactMixin(models.Model):

    status = models.CharField(u'ваш статус', choices=STATUS, max_length=255, default='owner')
    phone = models.CharField(u'моб. телефон', max_length=255)
    contact_name = models.CharField(u'контактное лицо', max_length=255, blank=True)
    email = models.CharField(u'контактный E-mail', max_length=255, blank=True, help_text=u'Будет опубликован')

    class Meta:

        abstract = True


class Board(AddressMixin, ContactMixin):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='%(class)s_%(app_label)s', null=True, blank=True)
    site = models.ForeignKey(Site, related_name='%(class)s_%(app_label)s', null=True, blank=True)
    type_realty = models.CharField(u'тип недвижимости который вы хотите сдать', db_index=True, choices=TYPE_REALTY, max_length=255, default='flat')
    name = models.CharField(u'название или рекламная фраза', max_length=255, help_text=u'Например: Номер с видом на море')
    text = models.TextField(u'описание объявления', blank=True)
    published = models.BooleanField(u'включено', db_index=True, default=True)
    image_main = models.ImageField(u'главная картинка', upload_to='image', null=True, blank=True)

    objects = BoardManager()

    class Meta:

        verbose_name = u'объявление'
        verbose_name_plural = u'объявления'
        ordering = ['-pk']

    def __unicode__(self):
        return self.name

    def get_image_main(self):

        if bool(self.image_main):
            return self.image_main
        else:
            return settings.BLANK_IMAGE

    @property
    def realty(self):
        return getattr(self, self.type_realty)

    @property
    def type_realty_name(self):
        return TYPE_REALTY_NAME.get(self.type_realty, '')

    @property
    def sleep(self):

        sleep = ''

        type_realty = self.realty

        if type_realty is not None:

            count = str(type_realty.sleep)
            last = count[-1:]

            sleep = u'%s {name}' % count
            last = int(last)

            if last <= 0 or (last >= 5 and last <= 9):
                sleep = sleep.format(name=u'спальных мест')
            elif last == 1:
                sleep = sleep.format(name=u'спальное место')
            elif last >= 2 and last <= 4:
                sleep = sleep.format(name=u'спальных места')

        return sleep

    @property
    def status_board(self):

        if self.published:
            return STATUS_BOARD.get(PUBLISHED, '')
        else:
            return STATUS_BOARD.get(UNPUBLISHED, '')

    @models.permalink
    def get_absolute_url(self):

        return 'board_detail', [self.type_realty, self.pk]

    def get_url(self):

        return u'http://' + unicode(self.site) + reverse('board_detail', args=[self.type_realty, self.pk])

    def save(self, *args, **kwargs):
        self.name = self.name.capitalize()
        super(Board, self).save(*args, **kwargs)


class Image(models.Model):

    board = models.ForeignKey(Board, related_name='%(class)s', null=True, blank=True)
    image = models.ImageField(u'картинка', upload_to=upload_dir_class_name, null=True, blank=True, validators=[max_file_size_validator], help_text=FILE_SIZE_HELP_TEXT)
    name = models.CharField(u'подпись', max_length=255, blank=True)
    main = models.BooleanField(u'главная', db_index=True, default=False)
    hash_image = models.CharField(u'хеш', max_length=255, blank=True)
    order = models.IntegerField(u'позиция', null=True, blank=True, default=0)

    objects = ImageManager()

    class Meta:

        verbose_name = u'изображение'
        verbose_name_plural = u'изображения'
        ordering = ['order', 'pk']

    def __unicode__(self):

        if self.name:
            return self.name
        else:
            return unicode(self.pk)


class Price(models.Model):

    board = models.OneToOneField(Board, related_name='%(class)s', null=True, blank=True)
    price = models.PositiveIntegerField(u'цена за сутки проживания', validators=[MinValueValidator(100)])
    prepay = models.PositiveIntegerField(u'предоплата', null=True, blank=True, validators=[MinValueValidator(0), MaxValueValidator(100)])
    clearing = models.BooleanField(u'возможен безналичный расчет')
    agreement = models.BooleanField(u'заселение по договору')
    documents = models.BooleanField(u'отчетные документы')
    checkin = models.CharField(u'время заезда', max_length=255, blank=True)
    checkout = models.CharField(u'расчетный час', max_length=255, blank=True)
    additional_bed = models.PositiveIntegerField(u'стоимость доп. спального места', null=True, blank=True)

    class Meta:

        verbose_name = u'цена'
        verbose_name_plural = u'цены'

    def __unicode__(self):
        return unicode(self.price)


class Discount(models.Model):

    board = models.ForeignKey(Board, related_name='%(class)s', null=True, blank=True)
    stay = models.PositiveIntegerField(u'срок проживания от', null=True, blank=True)
    discount = models.PositiveIntegerField(u'скидка', null=True, blank=True, validators=[MinValueValidator(0), MaxValueValidator(100)])
    conditions = models.CharField(u'условия', max_length=255, blank=True)

    class Meta:

        verbose_name = u'скидка'
        verbose_name_plural = u'скидки'
        ordering = ['discount']

    def __unicode__(self):
        return unicode(self.discount) + u'%'

    @property
    def stay_view(self):

        stay = ''

        if self.stay is not None:

            stay = str(self.stay)
            last = stay[-1:]
            stay = u'при проживании от %s {name}.' % stay

            if last == 1:
                stay = stay.format(name=u'дня')
            else:
                stay = stay.format(name=u'дней')

        return stay


class PriceMonth(models.Model):

    board = models.ForeignKey(Board, related_name='%(class)s', null=True, blank=True)

search/models.py
from django.db import models

# Create your models here.

search/forms.py
# -*- coding: utf-8 -*-
from haystack.forms import SearchForm as HaystackSearchForm


class SearchForm(HaystackSearchForm):

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)

        q = self.fields['q']
        q.widget.attrs.update({'placeholder': u'Я ищу...'})

search/views.py
# -*- coding: utf-8 -*-
from elasticstack.views import SearchView
from haystack.query import SearchQuerySet
from forms import SearchForm


class SearchModelMixin(object):

    def get_context_data(self, **kwargs):

        context = super(SearchModelMixin, self).get_context_data(**kwargs)

        if self.model is not None:

            object_list = context.get('object_list', [])
            object_pks = map(lambda x: int(x.pk), object_list)
            object_list = self.model.objects.published().filter(pk__in=object_pks)

            context['object_list'] = object_list

        return context


class SearchListView(SearchView):

    object_list = None
    form_class = SearchForm
    queryset = SearchQuerySet()

    def get_context_data(self, **kwargs):

        context = super(SearchListView, self).get_context_data(**kwargs)

        context['count'] = self.queryset.count

        return context


class SearchModelListView(SearchModelMixin, SearchListView):

    model = None

board/templates/board/board_create.html
{% extends "base.html" %}

{% block title %}Сдать недвижимость для отдыха {% if request.site.city %}в {{ request.site.city.where }}{% endif %}{% endblock %}
{% block header %}Выберите тип недвижимости, который хотите сдать{% endblock %}

{% block content %}

    {% if type_realty_all %}
    <ul>
        {% for k, v in type_realty_all %}
            <li><a href="{% url 'board_create' k %}">{{ v }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}

{% endblock %}

board/templates/board/board_list.html
{% extends "base.html" %}
{% load image_tags board_tags %}

{% block header %}{% if from_user %}Пользователь:{% if from_user.profile.name %}{{ from_user.profile.name }},{% endif %} все предложения{% else %}{% if query %}Результатов поиска ({{ count }}){% endif %}{% endif %}{% endblock %}

{% block content %}
{% filter_form %}

{% if object_list %}

<div class="board_list">
    {% for object in object_list %}
        <div class="col_12 item">

            <a href="{{ object.get_absolute_url }}" class="h3 preview" title="{{ object.type_realty_name }} {{ object.name }}"><img src="{{ object.get_image_main|crop:'356x200' }}" alt="{{ object.name }}" align="left" class="pull-left"/> <span class="link-text">{{ object }}</span>
              <div class="pull-right price">{{ object.price }} <i class="fa fa-rub"></i> <span class="gray">в сутки</span></div>
            </a>

            <div><b>{{ object.type_realty_name }}</b>: {{ object.address }}</div>
            <div>{{ object.sleep }}</div>
            {% if object.metro %}
            <div>До метро: {{ object.metro }} мин. {{ object.get_move_metro_display|lower }}</div>
            {% endif %}
            {% if object.type_beach %}
            <div>
              Пляж: {{ object.get_type_beach_display }},
              {% if object.beach %}
                {{ object.beach }} мин. {{ object.get_move_beach_display|lower }}
              {% endif %}
            </div>
            {% endif %}

            <a href="{{ object.get_absolute_url }}" class="button green">Смотреть</a>
            <div class="clear"></div>
            <hr />
        </div>
    {% endfor %}
</div>

    {% include 'pagination_include.html' %}

{% else %}
Объявлений нет. {% if type_realty %}Вы можете <a href="{% url 'board_create' type_realty %}">добавить своё</a>.{% endif %}
{% endif %}

{% endblock %}

{% block top_extend %}
    {% search_form %}
{% endblock %}

board/templates/board/board_list_mini.html
{% load image_tags %}

{% for object in object_list %}
    <div class="col_12 item">

        <a href="{{ object.get_absolute_url }}" class="h3 preview" title="{{ object.type_realty_name }} {{ object.name }}"><img src="{{ object.get_image_main|crop:'356x200' }}" alt="{{ object.name }}" align="left" class="pull-left"/> <span class="link-text">{{ object }}</span>
          <div class="pull-right price">{{ object.price }} <i class="fa fa-rub"></i> <span class="gray">в сутки</span></div>
        </a>

        <div><b>{{ object.type_realty_name }}</b>: {{ object.address }}</div>
        <div>{{ object.sleep }}</div>
        {% if object.metro %}
        <div>До метро: {{ object.metro }} мин. {{ object.get_move_metro_display|lower }}</div>
        {% endif %}
        {% if object.type_beach %}
        <div>
          Пляж: {{ object.get_type_beach_display }},
          {% if object.beach %}
            {{ object.beach }} мин. {{ object.get_move_beach_display|lower }}
          {% endif %}
        </div>
        {% endif %}

        <a href="{{ object.get_absolute_url }}" class="button green">Смотреть</a>
        <div class="clear"></div>
        <hr />
    </div>
{% endfor %}

board/templates/board/change_site.html
<div class="hover change_site">

    <a class="button" href="/" onclick="return false;">
        {% if current_site %}
            {{ current_site.name }}
        {% else %}
            Выбрать город
        {% endif %}
        <i class="fa fa-chevron-down"></i>
    </a>

    <ul class="menu vertical right">
        {% for x in sites %}
            <li><a href="http://{{ x }}/">{{ x.name }}</a></li>
        {% endfor %}
    </ul>

</div>

board/templates/board/filter_form.html
<div class="col_12 filter-form">
    <form method="GET" action="">
        Сортировать: {{ form.as_p }}
        {% for k, v in request.GET.items %}
            {% if k not in form.fields and k != 'filter_submit' and k != 'page' %}
                <input type="hidden" name="{{ k }}" value="{{ v }}" />
            {% endif %}
        {% endfor %}
        <input type="hidden" name="filter_submit" class="filter-submit"/>
    </form>
    <br />
</div>

board/templates/board/search_form.html
<div class="col_12 search">
    <form action="{% url 'search_list' %}" method="GET">
        <div class="col_10 alpha">
            {{ form.q }}
        </div>
        <div class="col_2 alpha">
            <button type="submit"><i class="fa fa-search"></i> Поиск</button>
        </div>
        <div class="clear"></div>
    </form>
</div>
<br />